// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjxraxwtjfxlzbvzpwec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqeHJheHd0amZ4bHpidnpwd2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTUzMzksImV4cCI6MjA2ODU3MTMzOX0.ADp6s5KlLApkkww0eSyOi8J7ULmqZuOZJ33zgiOnSx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});